### ISSUE TITLE
Problem if generating code

### ISSUE THREAD

**Issue by kbaraniak** [codecauldron/simple-xor-encryption-php#1]
**My Output:**
`<br />
<b>Fatal error</b>:  Uncaught Error: Class 'EncryptionUtil' not found in C:\xampp\htdocs\mypage\simple-xor-encryption-php-master\demo\do.php:12
Stack trace:
#0 {main}
  thrown in <b>C:\xampp\htdocs\mypage\simple-xor-encryption-php-master\demo\do.php</b> on line <b>12</b><br />`

**Comment by mobergio** [comment]
Correct, I added a namespace to the class but never updated the demo.

In `do.php` add the following line above the `require` line.
```
namespace CodeCauldron\Security\Encryption;
```

I will push in a fix when I get home from work.

Good catch. Let me know if this helps.

**Comment by kbaraniak** [comment]
Thanks for suggestion, doesn't work for me:

**If Use (require above & namespace)**
`<br />
<b>Fatal error</b>:  Namespace declaration statement has to be the very first statement or after any declare call in the script in <b>C:\xampp\htdocs\mypage\simple-xor-encryption-php-master\demo\do.php</b> on line <b>3</b><br />
`
**If Use (namespace)**
`<br />
<b>Fatal error</b>:  Uncaught Error: Class 'CodeCauldron\Security\Encryption\EncryptionUtil' not found in C:\xampp\htdocs\mypage\simple-xor-encryption-php-master\demo\do.php:12
Stack trace:
#0 {main}
  thrown in <b>C:\xampp\htdocs\mypage\simple-xor-encryption-php-master\demo\do.php</b> on line <b>12</b><br />`

**Edit : Thank for suggestion, this work**

**Comment by kbaraniak** [comment]
Working Code for me 

**`<?php`**
`namespace CodeCauldron\Security\Encryption;`
`require "../src/EncryptionUtil.php";`


`$key = $_POST["key"];`
`$method = (int) $_POST["method"];`
`$message = $_POST["message"];`
`$iterations = (int) $_POST["iterations"];`

`if ($method === 1) {`
    `$tmp = $message;`
    `for ($i = 0; $i < $iterations; $i++) {`
        `$tmp = EncryptionUtil::encrypt($tmp, $key);`
   ` }`
    `echo base64_encode($tmp);`
`} else {`
    `$tmp = base64_decode($message);`
    `for ($i = 0; $i < $iterations; $i++) {`
        `$tmp = EncryptionUtil::decrypt($tmp, $key);`
    `}`
    `echo $tmp;`
`}`*

**Comment by mobergio** [comment]
Yes you need to add it before the require line.
